<?php declare(strict_types=1);
/**
 * Database.php
 *
 * (C) 2025 by Eylem Ugurel
 *
 * Licensed under a Creative Commons Attribution 4.0 International License.
 *
 * You should have received a copy of the license along with this work. If not,
 * see <http://creativecommons.org/licenses/by/4.0/>.
 */

namespace Harmonia\Systems\DatabaseSystem;

use \Harmonia\Patterns\Singleton;

use \Harmonia\Config;
use \Harmonia\Logger;
use \Harmonia\Systems\DatabaseSystem\Proxies\MySQLiResult;
use \Harmonia\Systems\DatabaseSystem\Queries\Query;

/**
 * Provides a central interface for working with databases.
 *
 * This class manages connections and executes queries on the application
 * database. Connection details are retrieved from the configuration.
 */
class Database extends Singleton
{
    /**
     * Represents the connection to the database server.
     *
     * This property is lazy-initialized. Therefore, never use this property
     * directly, use the `connection` method instead.
     *
     * @var ?Connection
     */
    private ?Connection $connection = null;

    #region public -------------------------------------------------------------

    /**
     * Executes a query on the database.
     *
     * @param Query $query
     *   The query object containing SQL and optionally its bindings.
     * @return ?ResultSet
     *   A `ResultSet` if the query executes successfully. For queries that
     *   produce a result set (such as `SELECT`, `SHOW`, `DESCRIBE`, `EXPLAIN`),
     *   the result contains rows. For queries that do not produce a result set
     *   (such as `INSERT`, `UPDATE`, `DELETE`, `REPLACE`), the result is empty.
     *   Returns `null` if a database connection is unavailable or if the query
     *   fails. In case of failure, the error is written to the log file.
     */
    public function Execute(Query $query): ?ResultSet
    {
        $connection = $this->connection();
        if ($connection === null) {
            return null;
        }
        try {
            $result = $connection->Execute($query);
            return new ResultSet($result);
        } catch (\RuntimeException $e) {
            Logger::Instance()->Error($e->getMessage());
            return null;
        }
    }

    /**
     * Retrieves the ID generated by the last `INSERT` query.
     *
     * @return int
     *   The auto-generated ID from the last successful `INSERT` query. Returns
     *   `0` if the last query was not an `INSERT`, if no `AUTO_INCREMENT` value
     *   was generated, or if a database connection is unavailable.
     */
    public function LastInsertId(): int
    {
        $connection = $this->connection();
        if ($connection === null) {
            return 0;
        }
        return $connection->LastInsertId();
    }

    /**
     * Retrieves the number of rows affected by the last `INSERT`, `UPDATE`,
     * `REPLACE`, or `DELETE` query.
     *
     * @return int
     *   The number of rows affected by the last modifying query. Returns `0` if
     *   no rows were affected. Returns `-1` if the query fails, or if a database
     *   connection is unavailable.
     */
    public function LastAffectedRowCount(): int
    {
        $connection = $this->connection();
        if ($connection === null) {
            return -1;
        }
        return $connection->LastAffectedRowCount();
    }

    /**
     * Executes a callable within a database transaction.
     *
     * This method initiates a transaction, executes the provided callback, and
     * commits the transaction if no exception is thrown. The return value of
     * the callback is then propagated as the result of the transaction. A
     * callback returning any value (including `false`) is considered a valid
     * outcome and will be returned after a successful commit. If an exception
     * occurs during execution or commit, the transaction is rolled back and
     * `false` is returned.
     *
     * @param callable $callback
     *   The callback function to execute within the transaction. It may return
     *   any value representing a valid business logic outcome, or throw an
     *   exception to signal an error.
     * @return mixed
     *   Returns the value from the callback if the transaction is committed
     *   successfully. Returns `false` if the connection is unavailable or if an
     *   exception occurs during the transaction.
     */
    public function WithTransaction(callable $callback): mixed
    {
        $connection = $this->connection();
        if ($connection === null) {
            return false;
        }
        try {
            $connection->BeginTransaction();
            $result = $callback();
            $connection->CommitTransaction();
            return $result;
        } catch (\Throwable $e) {
            Logger::Instance()->Error($e->getMessage());
            try {
                $connection->RollbackTransaction();
            } catch (\Throwable $e) {
                Logger::Instance()->Error($e->getMessage());
            }
        }
        return false;
    }

    /**
     * Escapes special characters in a string for use in SQL statements.
     *
     * This method is intended for use in SQL queries where parameter binding
     * is not supported by the database engine (e.g., `SHOW DATABASES LIKE`).
     * It helps prevent SQL injection by escaping input values.
     *
     * The returned value is not quoted automatically. It is the caller's
     * responsibility to wrap the result in single quotes when embedding it
     * directly in a SQL string.
     *
     * #### Example
     * ```php
     * $sql = "SHOW DATABASES LIKE '{$database->EscapeString($name)}'";
     * ```
     *
     * @param string $string
     *   The string to be escaped.
     * @return string
     *   The escaped string, safe for use in SQL contexts when properly quoted.
     *   If the connection is unavailable, an empty string is returned.
     */
    public function EscapeString(string $string): string
    {
        $connection = $this->connection();
        if ($connection === null) {
            return '';
        }
        return $connection->EscapeString($string);
    }

    #endregion public

    #region private ------------------------------------------------------------

    /**
     * Lazily initializes and retrieves the database connection.
     *
     * This method connects to the database management system (DBMS) and selects
     * the default database. All required connection details are obtained from
     * the application configuration.
     *
     * @return ?Connection
     *   The established database connection, or `null` if the connection fails.
     */
    private function connection(): ?Connection
    {
        if ($this->connection === null) {
            $config = Config::Instance();
            try {
                $connection = $this->_new_Connection(
                    $config->OptionOrDefault('DatabaseHost', ''),
                    $config->OptionOrDefault('DatabaseUsername', ''),
                    $config->OptionOrDefault('DatabasePassword', ''),
                    $config->Option('DatabaseCharset')
                );
            } catch (\RuntimeException $e) {
                Logger::Instance()->Error($e->getMessage());
                return null;
            }
            try {
                $connection->SelectDatabase(
                    $config->OptionOrDefault('DatabaseName', '')
                );
            } catch (\RuntimeException $e) {
                Logger::Instance()->Error($e->getMessage());
                return null;
            }
            $this->connection = $connection;
        }
        return $this->connection;
    }

    #endregion private

    #region protected ----------------------------------------------------------

    /** @codeCoverageIgnore */
    protected function _new_Connection(string $host, string $username,
        string $password, ?string $charset): Connection
    {
        return new Connection($host, $username, $password, $charset); // may throw
    }

    #endregion protected
}
